# EMBEDDED SERVER CONFIGURATION
server:
   port: 9091
   contextPath: /
   servlet:
      contextPath: /rest

# SPRING CONFIG - DATASOURCE - LIQUIBASE
spring:
   config:
      name: ms-products
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
   spring:
      datasource:
         url: jdbc:h2:mem:testdb
   jpa:
      defer-datasource-initialization: true
      show-sql: true
      
management:
   endpoints:
      web:
         exposure: 
            include:*
      
