# EMBEDDED SERVER CONFIGURATION
server:
   port: 9091
   servlet:
      contextPath: /base-project/rest

# SPRING CONFIG - DATASOURCE - LIQUIBASE
spring:
   config:
      name: ms-products
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
   datasource:
      # CONFIG MYBATIS
      votre:
         driverClassName: com.ibm.as400.access.AS400JDBCDriver
         url: jdbc:as400://votre.leonisa.com:8471/BDVOTRE;prompt=false;password=${DS_VOTRE_PASS};user=${DS_VOTRE_USER}
         libraries: ${DS_VOTRE_LIBRARIES}
         hikari:
            connectionTimeout: 30000 
            idleTimeout: 600000
            maxLifetime: 1800000
#      jpa:
#         url: jdbc:h2:mem:testdb
#         driver-class-name: org.h2.Driver         
#         defer-datasource-initialization: true
#         show-sql: true
         
# PostgreSQL DB - "bar"
      bar:
         datasource:
            url: jdbc:postgresql://localhost:5432/client?currentSchema=public
            username: postgres
            password: 12345678
            driver-class-name: org.postgresql.Driver
      
management:
   endpoints:
      web:
         exposure: 
            include:*

# CONFIG FEING      
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


logging:
   level:
      root: debug
      org: 
         springframework:
            web:   info
      