# EMBEDDED SERVER CONFIGURATION
server:
   port: 9091
   servlet:
      contextPath: /base-project/rest

# SPRING CONFIG - DATASOURCE - LIQUIBASE
spring:
   config:
      name: ms-products
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
   datasource:
      url: jdbc:h2:mem:testdb
      # CONFIG MYBATIS
      votre:
         driverClassName: com.ibm.as400.access.AS400JDBCDriver
         url: jdbc:as400://votre.leonisa.com:8471/BDVOTRE;prompt=false;password=${DS_VOTRE_PASS};user=${DS_VOTRE_USER}
         libraries: ${DS_VOTRE_LIBRARIES}
         hikari:
            connectionTimeout: 30000 
            idleTimeout: 600000
            maxLifetime: 1800000
   jpa:
      defer-datasource-initialization: true
      show-sql: true
      
management:
   endpoints:
      web:
         exposure: 
            include:*

# CONFIG FEING      
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


logging:
   level:
      root: debug
      org: 
         springframework:
            web:   info
      